apiVersion: v1
kind: Service
metadata:
  name: big-ai-team
  namespace: big-ai-team
  labels:
    app: big-ai-team
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: big-ai-team