"""Add feedback table

Revision ID: cb3edb2b7d49
Revises: 56839bf7ef0f
Create Date: 2026-04-14 23:51:20.954077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3edb2b7d49'
down_revision: Union[str, Sequence[str], None] = '56839bf7ef0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if feedback table already exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'feedback' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('feedback',
        sa.Column('id', sa.UUID(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('task_id', sa.UUID(), nullable=True),
        sa.Column('skill_name', sa.String(length=64), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('feedback_type', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
